### DISCUSSION TITLE
Getting error trying to do something like "Factor-Conditional Settings: Python Version" section

### DISCUSSION THREAD

**Discussion by qsebas** [ymyzk/tox-gh-actions#174] [Q&A] [answered]
Hi, I'm quite new on developing open-source projects on GH (I have more xp on private projects in stand-alone Gitlab)
I'm working on very simple packages more focused on GH-tox-deploy configurations.

https://github.com/karpyncho/formdata-null-middleware

I have had a version working with tox-dev/tox-gh package and several python versions

Then I intented to include different django versions in my test matrix.. I've make changes in my tox.ini file

```ini
[tox]
requires =
    setuptools >= 40.8.0
isolated_build = True
envlist = linters,
          py36-django{2,3},
          py37-django{2,3},
          py38-django{2,3,4},
          py39-django{2,3,4},
          py310-django{3,4},
          py311-django{4},
          py310-cov

[testenv:linux]
platform = linux
basepython =
    py311: python3.11
    py310: python3.10
    py39: python3.9
    py38: python3.8
    py37: python3.7
    py36: python3.6

[gh]
python =
    3.7 = py37
    3.8 = py38
    3.9 = py39
    3.10 = py310-cov, linters
    3.11 = py311
```
This is working on my computer as expected...

but when I've intended to change the check.yml, i've realized that tox-gh won' t support that feature, but I've found this package. In the documentation says:

#### Factor-Conditional Settings: Python Version
The following configuration will create 2 jobs when running the workflow on GitHub Actions.
- On Python 3.7 job, tox runs `py37-django22` and `py37-django32` environments
- On Python 3.8 job, tox runs `py38-django32` environment
- 
`tox.ini`:
```ini
[tox]
envlist = py37-django{22,32}, py38-django32

[gh-actions]
python =
    3.7: py37
    3.8: py38

[testenv]
```

that is **exactly** what I need, but I've configured my ini file (mainly changed [gh] section to [gh-actions]:

tox.ini:
```ini
[tox]
requires =
    setuptools >= 40.8.0
isolated_build = True
envlist = linters,
          py36-django{2,3},
          py37-django{2,3},
          py38-django{2,3,4},
          py39-django{2,3,4},
          py310-django{3,4},
          py311-django{4},
          py310-cov

[testenv:linux]
platform = linux
basepython =
    py311: python3.11
    py310: python3.10
    py39: python3.9
    py38: python3.8
    py37: python3.7
    py36: python3.6

[gh-actions]
python =
    3.7 = py37
    3.8 = py38
    3.9 = py39
    3.10 = py310-cov, linters
    3.11 = py311
```
And changed check.yml installing tox-gh-actions
check.yml
```yml
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
        py: ["3.11", "3.10", "3.9", "3.8", "3.7"]

    steps:
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v3
      - name: Install tox-gh-actions
        run: python -m pip install tox-gh-actions
      - name: Setup test suite
        run: tox r -vv --notest
      - name: Run test suite
        run: tox r --skip-pkg-install
        env:
          PYTEST_ADDOPTS: "-vv --durations=10"
```
when i run it on GH i get 

    return {k: StrConvert.to_env_list(v).envs for k, v in parse_dict(value).items()}
    File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/tox_gh_actions/plugin.py", line 264, in parse_dict
    return dict((k.strip(), v.strip()) for k, v in pairs)
    File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/tox_gh_actions/plugin.py", line 264, in <genexpr>
    return dict((k.strip(), v.strip()) for k, v in pairs)
    ValueError: not enough values to unpack (expected 2, got 1)
    Error: Process completed with exit code 1.

(full error in https://github.com/karpyncho/formdata-null-middleware/actions/runs/4704826744/jobs/8344787851 )

I' ve no clue on how to fix it

PS: excuse my English, I'm not a native speaker
