### DISCUSSION TITLE
Tox step not executed

### DISCUSSION THREAD

**Discussion by lu-maca** [ymyzk/tox-gh-actions#180] [Q&A] [answered]
Hi,

I'm trying to set up a workflow that uses tox to run tests for my package.

The workflow file that I'm using is the same from the README of this repository:
```yaml
name: Tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: tox 
```

However, during the "Test with tox" step, tests are not executed correctly (as far as I can tell) and the following error is raised:
`py: tox-gh-actions couldn't understand the parallel option. ignoring the given option: 0`
![immagine](https://github.com/ymyzk/tox-gh-actions/assets/65252677/80582e58-b395-4214-9569-5af99f612baf)

Am I doing something wrong?

[This](https://github.com/lu-maca/py-packed-struct/tree/test-gh-workflows) is the branch in which I'm trying to trigger the action. [This](https://github.com/lu-maca/py-packed-struct/actions/runs/5431978874) is a failed action.

Thanks,
Luca
