### ISSUE TITLE
Arbitrary Environment Factor Support?

### ISSUE THREAD

**Issue by rlizzo** [ymyzk/tox-gh-actions#10]
First off, I'd like to express my appreciation and support of this project! It's a fairly interesting tool which performs well for my application. Kudos to the dev team!

I'm writing to see if it's possible to select runs for some complex generative envlist based on more factors than just `"python"`? 

For example:

```
#tox.ini

[tox]
envlist =
    clean,
    docs,
    py{36,37}-cov{yes,no}-ml{yes,no},
    report
```

```
#.github/workflows/toxtest.yml

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: [3.6, 3.7]

...
```

I can only use `tox-gh-actions` to select environmens based on the python version in the build matrix. (by including the following in my `tox.ini` file

```
#tox.ini

[gh-actions]
python =
    3.6: py36-mlyes,report
    3.7: py37-mlno,report
```

Which runs `py36-covyes-mlyes, py36-covno-mlyes, report` and `py37-covyes-mlyes, py37-covno-mlyes, report` for python 3.6 and 3.7, respectively. 

I would like to be able to include additional factor specifiers in the workflow job matrix which map to a reduced set of toxenvs from the full list. 

Something like

```
#.github/workflows/toxtest.yml

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: [3.6, 3.7]
        coverage: [yes, no]  # new matrix parameter

...
```

```
#tox.ini

[gh-actions]
python,coverage =
    3.6,yes: py36-covyes,report
    3.6,no: py36-covno
    3.7,yes: py37-covyes,report
    3.7,no: py37-covno
```

This doesn't seem possible in the current version, but I may be mistaken? 

Any tips on how to support such a workflow?

**Comment by ymyzk** [comment]
This is not possible with the current version but it's a good idea. I'll consider a way to support this type of requirements.

**Comment by rlizzo** [comment]
Thanks for the reply! 

If you can suggest some prior material to start from, and any considerations that need to be made for the current library requirements I'd be happy to take a stab at making a PR. Let me know!

**Comment by ymyzk** [comment]
@rlizzo, thanks for volunteering! I could finally made a PR for your request. #20 I think it can cover your use case like the following:

```
#.github/workflows/toxtest.yml

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version: [3.6, 3.7]
        coverage: [yes, no]  # new matrix parameter
    steps:
    ....
    - name: Test with tox
      run: tox
      env:
        COVERAGE: ${{ matrix.coverage }}
    ....

#tox.ini

[gh-actions]
python =
    3.6: py36, report
    3.7: py37, report

[gh-actions:env]
COVERAGE =
    yes: covyes, report
    no: covno
```
