### ISSUE TITLE
Update README Examples for Python 3.10

### ISSUE THREAD

**Issue by johnthagen** [ymyzk/tox-gh-actions#104]
Python 3.10 requires quotes around `"3.10"` in YAML:

```yaml
jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
```

I would recommend for consistency all of the `python-version` specifiers be updated with quotes, as above. This will reduce surprises for users down the road.

- https://github.com/actions/setup-python/issues/160#issuecomment-724485470
