### ISSUE TITLE
Cannot find matcher.json after update to 2.9.0

### ISSUE THREAD

**Issue by da1910** [ymyzk/tox-gh-actions#113]
**Describe the bug**
After the release of tox-gh-actions 2.9.0 our Github Actions CI is failing with an error that matcher.json cannot be found:

![image](https://user-images.githubusercontent.com/12086549/148753547-edacbbf7-f657-4b89-bbff-477975f247ba.png)

**To Reproduce**
* GitHub Actions configuration
```
test:
    name: Unit test on supported platforms
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
```
* tox and tox-gh-actions configuration
```
[tox]
envlist = py36,py37,py38,py39,py310
isolated_build = True
[gh-actions]
python =
    3.6: py36
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310
[testenv]
deps =
   ...
commands = pytest ./tests
```

**Expected behavior**
I expect the CI run to complete without error
