### ISSUE TITLE
Python 3.6 environment not found, but works for 3.7, 3,8, 3,9...

### ISSUE THREAD

**Issue by EmilStenstrom** [ymyzk/tox-gh-actions#146]
First of all, thank you for providing this excellent library! I don't take your work or help for granted! :)

**Question**
tox-gh-actions does not find my Python 3.6 environment. I'm getting the error "Warning: WARNING: tox-gh-actions couldn't find environments matching the provided factors from envlist. Please use `tox -vv` to get more detailed logs."

I have tried googling this, but I only find examples with configs similar to mine. Also, since the other environments work, I really struggle to understand how 3.6 is different. Would you mind helping me getting my tests for 3.6 run on GitHub Actions?

**Context**
This is for an open source-project, so the full run, with all config is available here:
https://github.com/EmilStenstrom/django-components/actions/runs/4518371119/jobs/7958205977

Researching this bug I found the fail_on_no_env option, which explains why I missed that we didn't have any tests for 3.6 run at all. Would much prefer to have this as the default. Here's the same run with this flag enabled:
https://github.com/EmilStenstrom/django-components/actions/runs/4518425680/jobs/7958298706

Relevant parts of [tox.ini](https://github.com/EmilStenstrom/django-components/blob/master/tox.ini)
```
[tox]
envlist =
  py36-django{32}
  py37-django{32}
  py38-django{32,40}
  py39-django{32,40}
  py310-django{40}
  flake8
  isort

[gh-actions]
python =
  3.6: py36
  3.7: py37
  3.8: py38
  3.9: py39
  3.10: py310, flake8, isort
fail_on_no_env = True
```

Relevant parts of [tests.yml](https://github.com/EmilStenstrom/django-components/blob/master/.github/workflows/tests.yml)
```
name: Run tests

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Run tests
      run: tox -vv
```
